### ISSUE TITLE
depends error in rpi4b+

### ISSUE THREAD

**Issue by ykla** [Re4son/RPi-Tweaks#11]
root@kali:~# apt install whiptail parted lua5.1 alsa-utils psmisc libraspberrypi0 libraspberrypi-dev libraspberrypi-doc libraspberrypi-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libraspberrypi0
E: Unable to locate package libraspberrypi-dev
E: Unable to locate package libraspberrypi-doc
E: Unable to locate package libraspberrypi-bin

OS: kali-linux-2019.3-rpi3-nexmon-64

**Comment by ghost** [comment]
Hello
Any luck?
Same issue with OS: kali-linux-2020.1-rpi3-nexmon-64

**Comment by ChrisTayl2018** [comment]
Having the same issue when trying to run Ubuntu 18.04 Server image on a raspberry pi 4b+. 

Setting up python-mock (2.0.0-3) ...
executing command [sudo -H apt-get install -y libraspberrypi0]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libraspberrypi0
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y libraspberrypi0] failed

**Comment by klezm** [comment]
For my rpi 3B+ I had the same issue with the nexmon image. With the "kali-linux-2020.2-rpi.img" it worked.
I just remember the repo from Re4son on the nexmon image was on another channel than on my current kali distro. Maybe you could change that?
On his website Re4son suggests you to add the following repo `deb http://http.re4son-kernel.com/re4son/ kali-pi main` but I have a different channel `deb http://http.re4son-kernel.com/re4son/ kali-pi armel` where the packages `libraspberrypi0` `libraspberrypi-dev` and `libraspberrypi-bin` are present.

**Comment by steev** [comment]
There are no libraspberrypi packages for 64bit currently.  That's why the dependency errors.

**Comment by steev** [comment]
If you want to run kalipi-config on the 64bit image, you'll need to do the following:

```
sudo su -
git clone https://github.com/raspberrypi/userland
cd userland
apt-get install --yes --allow-change-held-packages cmake
./buildme --aarch64
cd
rm -rf /root/userland

cat << EOF >> /etc/profile.d/vc.sh
# Add /opt/vc/bin to the PATH for all users.
if ! echo "$PATH" | tr : '\n' | grep -q "^/opt/vc/bin$"; then
  PATH="/opt/vc/bin:$PATH"
fi
EOF

cat << EOF >> /etc/ld.so.conf.d/raspi-userland.conf
# Add raspberrypi libraries to ldconfig path
/opt/vc/lib
EOF

cat << EOF >> /etc/udev/rules.d/99-vchiq-permissions.rules
SUBSYSTEM=="vchiq", GROUP="video", MODE="0660"
SUBSYSTEM=="vc-sm", GROUP="video", MODE="0660"
SUBSYSTEM=="bcm2708_vcio", GROUP="video", MODE="0660"
EOF
```
reboot

Then, because we already have the userland, you don't need those packages, so you should be able to just do

`apt install whiptail parted lua5.1 alsa-utils psmisc`

Change line 34 of the kalipi-config script to show that it supports arm64 as well (it should look like below):

`if [ "$ARCH" = "armhf" ] || [ "$ARCH" = "armel" ] || [ "$ARCH" = "arm64" ]; then`
